### ISSUE TITLE
`.getContent` on the users' behalf with `DocString` parameters

### ISSUE THREAD

**Issue by danielmiladinov** [danielmiladinov/burpless#4]

**Comment by jakent** [comment]
With your built in `DocString` `edn` support I think this enhancement is no longer needed. 

- https://github.com/danielmiladinov/burpless/blob/master/test-resources/features/custom-docstring-types/from-edn.feature#L13
- https://github.com/danielmiladinov/burpless/blob/master/test/custom_docstring_types_test.clj#L36

**Comment by danielmiladinov** [comment]
Oh, right, of course!
